# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKJ7OIHIO_QAYbmx-hl_mZ-rlBWTpHGc
"""

!pip install "mlflow<3" dagshub pandas numpy scikit-learn

# kriteria-2/modelling.py
import mlflow
import mlflow.sklearn
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import dagshub
import os

# konfigurasi DAGsHub
dagshub.init(repo_owner='Raziffff', repo_name='Prediksi_Asuransi', mlflow=True)
mlflow.set_experiment("Prediksi_Asuransi")

# load data
train_df = pd.read_csv("insurance_train_preprocessed.csv")
test_df  = pd.read_csv("insurance_test_preprocessed.csv")

X_train, y_train = train_df.drop(columns=["target"]), train_df["target"]
X_test,  y_test  = test_df.drop(columns=["target"]),  test_df["target"]

# training + autolog
with mlflow.start_run(run_name="rf_autolog"):
    mlflow.sklearn.autolog()
    model = RandomForestRegressor(random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2  = r2_score(y_test, y_pred)

    print(f"MSE: {mse:.2f}")
    print(f"R2: {r2:.3f}")