# -*- coding: utf-8 -*-
"""modelling_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bZozt7figFIvk9G7IzDHXzUneZJHFXJ
"""

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc, classification_report
from sklearn.utils import estimator_html_repr
from imblearn.over_sampling import SMOTE
import mlflow
import mlflow.sklearn
import matplotlib.pyplot as plt
import dagshub
import seaborn as sns
import os
import warnings

warnings.filterwarnings("ignore")

dagshub.init(
  repo_owner="Raziffff",
  repo_name="Attrition",
  mlflow=True
  )

warnings.filterwarnings("ignore")

mlflow.set_tracking_uri(
"https://dagshub.com/Raziffff/Attrition.mlflow"
                  )
mlflow.set_experiment("Attrition_Tuned_Models")

# --- LOAD DATA ---
data_path = 'processed_data.csv'
df = pd.read_csv(data_path)
X = df.drop(columns=['Attrition'])
y = df['Attrition']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
    )

# --- SMOTE ---
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# --- Grid Search Parameters ---
param_grid = {
  'C': [0.1, 1, 10],
  'kernel': ['linear', 'rbf'],
  'gamma': ['scale', 'auto']
}

grid = GridSearchCV(SVC(probability=True), param_grid, cv=3, scoring='accuracy')
grid.fit(X_train_resampled, y_train_resampled)

# --- MLflow Manual Logging ---
with mlflow.start_run(run_name="SVM_Tuning_GridSearch_Manual_Logging"):
  best_model = grid.best_estimator_

  y_pred = best_model.predict(X_test)
  y_pred_proba = best_model.predict_proba(X_test)[:, 1]

  acc = accuracy_score(y_test, y_pred)
  prec = precision_score(y_test, y_pred)
  rec = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)

# Manual Logging - Parameters
  mlflow.log_param("best_C", best_model.C)
  mlflow.log_param("best_kernel", best_model.kernel)
  mlflow.log_param("best_gamma", best_model.gamma)
  mlflow.log_param("cv_folds", 3)
  mlflow.log_param("test_size", 0.2)
  mlflow.log_param("smote_applied", True)
  mlflow.log_param("random_state", 42)

# Manual Logging - Metrics
  mlflow.log_metric("accuracy", acc)
  mlflow.log_metric("precision", prec)
  mlflow.log_metric("recall", rec)
  mlflow.log_metric("f1_score", f1)
  mlflow.log_metric("best_cv_score", grid.best_score_)

# Manual Logging - Model
mlflow.sklearn.log_model(best_model, "svm_model")

# --- Generate Estimator HTML (Like Autolog) ---
estimator_html = estimator_html_repr(best_model)
estimator_path = "artifacts/estimator.html"
os.makedirs("artifacts", exist_ok=True)
with open(estimator_path, 'w', encoding='utf-8') as f:
  f.write(estimator_html)
mlflow.log_artifact(estimator_path)

# --- Generate Confusion Matrix ---
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
cm_path = "artifacts/confusion_matrix.png"
plt.savefig(cm_path)
mlflow.log_artifact(cm_path)
plt.close()

# --- Generate ROC Curve (Artifact 1) ---
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,4))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.tight_layout()
roc_path = "artifacts/roc_curve.png"
plt.savefig(roc_path)
mlflow.log_artifact(roc_path)
mlflow.log_metric("roc_auc", roc_auc)
plt.close()

# --- Generate Model Summary Report (Artifact 2) ---
report_content = f"""
SVM Model Performance Summary Report
=====================================

Model Configuration:
- Algorithm: Support Vector Machine (SVM)
- Best Parameters: C={best_model.C}, kernel={best_model.kernel}, gamma={best_model.gamma}
- Cross-validation folds: 3
- Best CV Score: {grid.best_score_:.4f}

Data Information:
- Training samples (after SMOTE): {len(X_train_resampled)}
- Test samples: {len(X_test)}
- Features: {len(X.columns)}
- SMOTE applied: Yes

Performance Metrics:
- Accuracy: {acc:.4f}
- Precision: {prec:.4f}
- Recall: {rec:.4f}
- F1-Score: {f1:.4f}
- ROC AUC: {roc_auc:.4f}

Classification Report:
{classification_report(y_test, y_pred)}

Confusion Matrix:
True Negatives:  {cm[0,0]}
False Positives: {cm[0,1]}
False Negatives: {cm[1,0]}
True Positives:  {cm[1,1]}

Grid Search Results:
Best Score: {grid.best_score_:.4f}
Best Parameters: {grid.best_params_}
"""

report_path = "artifacts/model_summary_report.txt"
with open(report_path, 'w') as f:
  f.write(report_content)
mlflow.log_artifact(report_path)

# --- Save Predictions CSV ---
pred_df = pd.DataFrame({
"y_true": y_test,
"y_pred": y_pred,
"y_pred_proba": y_pred_proba
 })
pred_path = "artifacts/predictions.csv"
pred_df.to_csv(pred_path, index=False)
mlflow.log_artifact(pred_path)

print("--- Best Model Evaluation ---")
print(f"Accuracy : {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall   : {rec:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC AUC  : {roc_auc:.4f}")
